server:
    port: 8080
    host: 0.0.0.0
hue:
    bridge_ip: 10.1.19.45
    application_key: Eo1Pq5khteLqcc1-8zoLDRUVnZ4UEsHPEIqgVJON
loxone:
    miniservers:
        - id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
          name: Miniserver
          ip: 10.1.19.40
          port: 7777
          udp_enabled: true
          http_enabled: true
          http_user: ""
          http_password: ""
          send_all: false
logging:
    level: debug
    format: json
mappings:
    - id: 0e5d9902-5bfb-4acd-8d40-d9bc9c1c7885
      name: Esszimmer - gedimmt
      loxone_id: esszimmer_mood_2
      hue_id: 629a4ea9-9367-4546-9a23-47c1813ea481
      hue_type: scene
      enabled: true
      description: Gedimmt
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 3270e500-8e65-4d0a-8fca-23932faf2245
      name: Esszimmer - Standard
      loxone_id: esszimmer_mood_1
      hue_id: 651b5bed-b6e1-4a4d-859f-5263ddf1d6b7
      hue_type: scene
      enabled: true
      description: Default
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 9fae4f12-d25b-4015-a046-5ed80aa39eb6
      name: Wohnzimmer - fernsehen
      loxone_id: wohnzimmer_mood_1
      hue_id: f254aa3a-74f6-4a1b-baa0-8199cb0e805a
      hue_type: scene
      enabled: true
      description: Fernsehen
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: b3eaca59-9772-4f27-9c83-4fcbf9a35d5d
      name: Wohnzimmer - entspannen
      loxone_id: wohnzimmer_mood_2
      hue_id: 621e4c7f-982c-4ea3-847f-7832444d8d34
      hue_type: scene
      enabled: true
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: b6eaf813-5794-4f52-ad8f-dd43aaf20ede
      name: Wohnzimmer- hell
      loxone_id: wohnzimmer_mood_3
      hue_id: c5d85fd1-98ac-4d25-a885-806c0eed0604
      hue_type: scene
      enabled: true
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 0badbff5-eb6e-4bb6-9398-a9efa0deffad
      name: Büro Stefan
      loxone_id: buero_stefan
      hue_id: 03091793-bb9e-44d3-a642-cf1b9e80b84c
      hue_type: group
      enabled: true
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 3062e59e-b937-4303-99d6-e0d0c8b1f0af
      name: Büro Stefan - Alle Lichter aus
      loxone_id: buero_stefan_mood_0
      hue_id: 03091793-bb9e-44d3-a642-cf1b9e80b84c
      hue_type: group
      enabled: true
      description: Mood 0 für Büro Stefan (Gruppe ausschalten)
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 577aca1d-a622-464f-8944-aa8f1cbb417e
      name: Büro Stefan - Standard
      loxone_id: buero_stefan_mood_1
      hue_id: a4001c7d-7f3b-443d-be06-605ed084b689
      hue_type: scene
      enabled: true
      description: Mood 1 für Büro Stefan
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 3d971174-4dc0-4c68-aa1c-4965a18692b9
      name: Büro Stefan - Energie tanken
      loxone_id: buero_stefan_mood_2
      hue_id: 9ee25b19-1aa8-4a9a-a366-59f2c6937ff3
      hue_type: scene
      enabled: true
      description: Mood 2 für Büro Stefan
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 7519f9a8-8624-4054-bf9b-d35f6e264614
      name: Büro Stefan - Entspannen
      loxone_id: buero_stefan_mood_3
      hue_id: 1120ef17-63d7-4b4d-bffa-b283a599a2eb
      hue_type: scene
      enabled: true
      description: Mood 3 für Büro Stefan
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 334262c6-a082-4a68-a8cc-859222d32e0d
      name: Büro Stefan - Ruhephase
      loxone_id: buero_stefan_mood_4
      hue_id: 7e1c4bca-69b6-48fc-9e13-b6a6cff092a2
      hue_type: scene
      enabled: true
      description: Mood 4 für Büro Stefan
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
    - id: 324ae01b-6b6c-451d-a29d-fdef70dc6a22
      name: Hue smart button 1 Button 1
      loxone_id: hue_smart_button_1_button_1
      hue_id: b7f450eb-8793-4a87-ae33-8ab31a8e2f14
      hue_type: sensor
      enabled: true
      miniserver_id: fb0dd0e7-0e53-4445-b785-f48f9948fb33
